### ISSUE TITLE
Cannot interact with a proxy contract [APE-1169]

### ISSUE THREAD

**Issue by raychangXrex** [ApeWorX/ape-arbitrum#18]
### ape version:

-  0.6.8

### ape plugins list:
-   notebook     0.6.0a1
-   solidity     0.6.3
-   tokens       0.6.0
-   infura       0.6.1
-   vyper        0.6.5
-   optimism     0.6.0
-   arbitrum     0.6.0
-   foundry      0.6.7
-   polygon      0.6.1
-   ganache      0.6.5
-   avalanche    0.6.2

### What went wrong?
I tried to interact with address '0x0180dee5Df18eBF76642e50FaaEF426f7b2874f7' which is a proxy contract  on arbitrum mainnet but got a contract type error.

command:
```
ape console --network arbitrum:mainnet -v DEBUG 
```

console:
```
from ape import Contract
Contract('0x0180dee5Df18eBF76642e50FaaEF426f7b2874f7' ) 
```

Then I got this error
```
  File "/Users/raychang/Desktop/aus_brownie/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/raychang/Desktop/aus_brownie/.venv/lib/python3.9/site-packages/ape/managers/chain.py", line 1114, in instance_at
    raise ChainError(f"Failed to get contract type for address '{contract_address}'.")

ERROR: (ChainError) Failed to get contract type for address '0x0180dee5Df18eBF76642e50FaaEF426f7b2874f7'.
```

### How can it be fixed?
I think it's due to the proxy contract since Contract works fine for other addresses. Have tried to use abi from the proxy one and the implemented one but still got same errors. need advice

**Comment by dtdang** [comment]
Problem solved, just needed to install etherscan plugin.
